modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/mrmelon54/enhanced_searchability/issues"
license = "GPL-3.0-only"

[[mods]]
modId = "enhanced_searchability"
version = "${version}"
displayName = "Enhanced Searchability"
authors = "MrMelon54"
description = "${description}"
logoFile = "/icon.png"

[[dependencies.enhanced_searchability]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.enhanced_searchability]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.enhanced_searchability]]
modId = "cloth_config"
mandatory = true
versionRange = "[${cloth_config_version},)"
ordering = "AFTER"
side = "BOTH"
